//
//  NotToDo+Extension.swift
//  NotToDo
//
//  Created by Bogdan on 2/14/21.
//

import Foundation


//nothing to do, NotToDo had an ID already
//we don't add the Identifiable conformance in NotToDo.swift because that was a file generated by AWS
//and we should not modify it
extension NotToDo: Identifiable {}

extension NotToDo: Equatable {
    public static func ==(lhs: NotToDo, rhs: NotToDo) -> Bool {
        return lhs.id == rhs.id && lhs.body == rhs.body
    }
}

extension NotToDo: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(id + body)
    }
}
